API_JWT/API_JWT/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('jwt/', views.empView.as_view(), name ='empEmail'),
]

API_JWT/CRUD_API/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt import views as jwt_views
from EMP import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
    path('api/token/',
         jwt_views.TokenObtainPairView.as_view(),
         name ='token_obtain_pair'),
    path('api/token/refresh/',
         jwt_views.TokenRefreshView.as_view(),
         name ='token_refresh'),
    path('', include('app.urls')),
]

API_JWT/API_JWT/models.py
from django.db import models

# Create your models here.

API_JWT/EMP/models.py
from django.db import models

class employee(models.Model):
    empID = models.CharField(max_length=20)
    empName = models.CharField(max_length=100)
    empEmail= models.EmailField()
    password=models.CharField(max_length=100)
    empAddress = models.CharField(max_length=15)
    class Meta:
        db_table = "employee"

API_JWT/EMP/forms.py
from django import forms
from .models import employee
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = employee
        fields = "__all__"

API_JWT/API_JWT/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated


class empView(APIView):
	permission_classes = (IsAuthenticated, )

	def get(self, request):
		content = {'message': 'empEmail, password'}
		return Response(content)

API_JWT/EMP/views.py
from django.shortcuts import render, redirect
from .forms import EmployeeForm
from .models import employee
# Create your views here.
def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request,'myapp/index.html',{'form':form})
def show(request):
    employees = employee.objects.all()
    return render(request,"myapp/show.html",{'employees':employees})
def edit(request, id):
    employee = employee.objects.get(id=id)
    return render(request,'myapp/edit.html', {'employee':employee})
def update(request, id):
    employee = employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'myapp/edit.html', {'employee': employee})
def destroy(request, id):
    employee = employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

API_JWT/EMP/templates/myapp/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/demo.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{employee.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee empID:</label>
    <div class="col-sm-4">
        <input type="text" name="empID" id="id_empID" required maxlength="20" value="{{ employee.empID }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee empName:</label>
    <div class="col-sm-4">
        <input type="text" name="empName" id="id_empName" required maxlength="100" value="{{ employee.empName }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee empEmail:</label>
    <div class="col-sm-4">
        <input type="email" name="empEmail" id="id_empEmail" required maxlength="254" value="{{ employee.empEmail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">password:</label>
    <div class="col-sm-4">
        <input type="text" name="password" id="id_password" required maxlength="15" value="{{ employee.password }}" />
    </div>
  </div>
        <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee empAddress:</label>
    <div class="col-sm-4">
        <input type="text" name="empAddress" id="id_empAddress" required maxlength="254" value="{{ employee.empAddress }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

API_JWT/EMP/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
   {% load static %}
    <link rel="stylesheet" href="{% static 'css/demo.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/emp">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Enter Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Id:</label>
    <div class="col-sm-4">
      {{ form.empID }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Name:</label>
    <div class="col-sm-4">
      {{ form.empName }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Email:</label>
    <div class="col-sm-4">
      {{ form.empEmail}}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">password:</label>
    <div class="col-sm-4">
      {{ form.password }}
    </div>
  </div>
        <div class="form-group row">
    <label class="col-sm-2 col-form-label">Employee Address:</label>
    <div class="col-sm-4">
      {{ form.empAddress }}
    </div>
    </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

API_JWT/EMP/templates/myapp/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/demo.css' %}"/>
</head>
<body>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Employee ID</th>
        <th>Employee Name</th>
        <th>Employee Email</th>
        <th>password</th>
         <th>Employee Address</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
{% for employee in employees %}
    <tr>
        <td>{{ employee.empID }}</td>
        <td>{{ employee.empName }}</td>
        <td>{{ employee.empEmail }}</td>
         <td>{{ employee.password }}</td>
        <td>{{ employee.empAddress}}</td>
        <td>
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>
            <a href="/delete/{{ employee.id }}">Delete</a>
        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
</body>
</html>